### PR TITLE
Update github action example with a real life example

### PR DESCRIPTION
**Pull request by nitanmarcel**
Added example of action name
Added example on starting on push
Added example of correct artifact naming. (The action will assume artifact.zip for the artifact name by default)

### CODE REVIEW

**Comment by nitanmarcel** [comment]
Silly me, this a action. But why? The PR shows how easy it gets to build the artifacts with clickable

**Comment by Fuseteam** [comment]
oh now i see what you mean

however this action allow one to pull a specific version of the clickable image and pin it to that version

both are valid methods, this is just the docker method

**Comment by Fuseteam** [comment]
hmmm apparently this is also an option: https://github.com/nanu-c/axolotl/blob/main/.github/workflows/package.yaml

**Comment by nitanmarcel** [comment]
> oh now i see what you mean
> 
> however this action allow one to pull a specific version of the clickable image and pin it to that version
> 
> both are valid methods, this is just the docker method

hmm you mean xD?

```
      - name: Install clickable
        run: |
          python3 -m pip install clickable-ut==7.4.0
```

**Comment by Fuseteam** [comment]
but that feels like so much to remember xD

**Pull request closed without merging**
